sudo: false
language: go
go:
  - "1.9"
  - "1.10"
  - "1.11"
  - tip
env:
  - GOOS=linux GOARCH=arm
  - GOOS=linux GOARCH=mips
  - GOOS=linux GOARCH=mipsle
  - GOOS=windows GOARCH=386
  - GOOS=darwin GOARCH=amd64
script:
  - go test -v
  - go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
